=== Corgan/UnknownMod/Data/_schema/CardbackDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CardbackDef",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "CardbackName": {
      "type": "string"
    },
    "CardbackTextId": {
      "type": "string"
    },
    "CardbackOrder": {
      "type": "integer"
    },
    "BaseCardback": {
      "type": "boolean"
    },
    "Locked": {
      "type": "boolean"
    },
    "ShowIfLocked": {
      "type": "boolean"
    },
    "RankLevel": {
      "type": "integer"
    },
    "Sku": {
      "type": "string"
    },
    "SteamStat": {
      "type": "string"
    },
    "AdventureLevel": {
      "type": "integer"
    },
    "ObeliskLevel": {
      "type": "integer"
    },
    "SingularityLevel": {
      "type": "integer"
    },
    "PdxAccountRequired": {
      "type": "boolean"
    },
    "HideInGame": {
      "type": "boolean"
    },
    "CardbackSubclass": {
      "type": "string"
    },
    "SpriteSource": {
      "type": "string"
    },
    "SpriteOverride": {
      "type": "string"
    }
  }
}

=== Corgan/UnknownMod/Data/mycelium_abyss/cardbacks/myceliumancerprocardback.json
{
  "Id": "myceliumancerProCardback",
  "CardbackName": "Sporebloom",
  "CardbackTextId": "",
  "CardbackOrder": 3,
  "BaseCardback": false,
  "Locked": false,
  "ShowIfLocked": false,
  "RankLevel": 40,
  "Sku": "",
  "SteamStat": "",
  "AdventureLevel": 0,
  "ObeliskLevel": 0,
  "SingularityLevel": 0,
  "PdxAccountRequired": false,
  "HideInGame": false,
  "CardbackSubclass": "myceliumancer",
  "SpriteSource": "",
  "SpriteOverride": "myc_cardback_pro"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/cardbacks/myceliumancerregularcardback.json
{
  "Id": "myceliumancerRegularCardback",
  "CardbackName": "Mycelial",
  "CardbackTextId": "",
  "CardbackOrder": 1,
  "BaseCardback": false,
  "Locked": false,
  "ShowIfLocked": false,
  "RankLevel": 8,
  "Sku": "",
  "SteamStat": "",
  "AdventureLevel": 0,
  "ObeliskLevel": 0,
  "SingularityLevel": 0,
  "PdxAccountRequired": false,
  "HideInGame": false,
  "CardbackSubclass": "myceliumancer",
  "SpriteSource": "",
  "SpriteOverride": "myc_cardback_regular"
}
