=== Corgan/UnknownMod/Data/_schema/CombatDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CombatDef",
  "type": "object",
  "properties": {
    "CombatId": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "NpcIds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "CombatTier": {
      "type": "string",
      "enum": [
        "T0",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "T6",
        "T7",
        "T8",
        "T9",
        "T10",
        "T11",
        "T12",
        "T13"
      ]
    },
    "Background": {
      "type": "string",
      "enum": [
        "Senenthia_Plains",
        "Senenthia_Forest",
        "Senenthia_Night",
        "Sectarium",
        "Velkarath_Stone",
        "Velkarath_Lava0",
        "Velkarath_Lavavolcan",
        "Velkarath_Lava2",
        "Spider_Lair",
        "Aquarfall_Main",
        "Aquarfall_Water",
        "Aquarfall_Boss",
        "Senenthia_Deepforest",
        "Void_Regular",
        "Void_Stairs",
        "Void_Obelisk",
        "Void_StairsClose",
        "Void_StairsClose2",
        "Void_RegularUP",
        "Void_ObeliskClose",
        "Void_ObeliskClose2",
        "Senenthia_Dia",
        "Senenthia_Tarde",
        "Senenthia_LobosTarde",
        "Senenthia_LobosNoche",
        "Senenthia_BosqueEntrada",
        "Senenthia_BosqueBoss",
        "Senenthia_Bosque",
        "Velkarath_Lava1",
        "Velkarath_Arena",
        "Velkarath_Cave",
        "Void_Boss",
        "Void_BossFinal",
        "Void_Obelisk_Lila",
        "Void_ObeliskClose2_Lila",
        "Void_Regular_Rosa",
        "Void_Stairs_Rosa",
        "Void_StairsClose_Rosa",
        "Void_StairsClose2_Rosa",
        "Void_Twins",
        "Faeborg_Armeria",
        "Faeborg_Bosque",
        "Faeborg_BosqueCastor",
        "Faeborg_Boss",
        "Faeborg_Ciudad",
        "Faeborg_Costa",
        "Faeborg_Rabbit",
        "Forge_Boss",
        "Forge_Mid",
        "Forge_Pared",
        "Sewers",
        "Wolfwars_Boss",
        "Wolfwars_Bree",
        "Wolfwars_Forest",
        "Wolfwars_Talado",
        "Wolfwars_Torre",
        "Ulminin_Arriba",
        "Ulminin_Arriba2",
        "Ulminin_Centro",
        "Ulminin_Centro2",
        "Ulminin_Desierto",
        "Ulminin_Desierto2",
        "Ulminin_DesiertoGusano",
        "Ulminin_Oasis",
        "Ulminin_Oasis2",
        "Ulminin_Primero",
        "Ulminin_Catacombs",
        "Ulminin_CatacombsBoss",
        "Ulminin_Pyramid",
        "Ulminin_PyramidBoss",
        "Uprising_LowEnergy",
        "Uprising_LowLava",
        "Uprising_Mid",
        "Uprising_MidElevator",
        "Uprising_Top",
        "Dread_Halfman",
        "Dread_Ship",
        "Sahti_Cavern",
        "Sahti_Kraken",
        "Sahti_Rust",
        "Sahti_Ship",
        "Sahti_ShipCloudy",
        "Sahti_ShipCloudyStorm",
        "Sahti_ShipStorm",
        "Sunken_BossBlood",
        "Sunken_BossHoly",
        "Sunken_BossThunder",
        "Sunken_Firstfloor",
        "Sunken_Firstflooraltar",
        "Sunken_Secondfloor",
        "Sunken_Secondflooraltar",
        "Castle_Interior",
        "Outskirts_Graveyard",
        "Castle_Interior_Night",
        "Courtyard_Day",
        "Courtyard_Night",
        "Graveyard_Day",
        "Forest_Day",
        "Forest_Night",
        "Archon_Throne_Room",
        "Siren_Queen_Throne_Room",
        "Dracula_Throne_Room",
        "Franky_Lab",
        "Senenthia_Dia_Nightmare",
        "Senenthia_BosqueEntrada_Nightmare",
        "Withered_Vale1",
        "Withered_Vale2",
        "Withered_Vale3",
        "Withered_ValeBoss",
        "GiraffeZebra",
        "HippoRhinoVillage",
        "WildCatofTerritory",
        "ArenaLionBossCombat",
        "AlphaElephantAndShamanBossCombat",
        "CrocodileMotherAndKidsBossCombat"
      ]
    },
    "CustomBackgroundId": {
      "type": "string"
    },
    "NpcRemoveInMadness0Index": {
      "type": "integer"
    },
    "HealHeroes": {
      "type": "boolean"
    },
    "IsRift": {
      "type": "boolean"
    },
    "StepSound": {
      "type": "string",
      "enum": [
        "Walk_Stone",
        "Walk_Grass",
        "Walk_Water",
        "None"
      ]
    },
    "NeverRandomizeEnemies": {
      "type": "boolean"
    },
    "RandomizeNpcPosition": {
      "type": "boolean"
    },
    "EventRequirementId": {
      "type": "string"
    },
    "NpcToSummonOnKilledId": {
      "type": "string"
    },
    "EventDataId": {
      "type": "string"
    },
    "CinematicId": {
      "type": "string"
    },
    "CombatBasedCorruptionCardId": {
      "type": "string"
    },
    "ThermometerTierId": {
      "type": "string"
    },
    "CombatMusic": {
      "type": "string"
    },
    "CombatEffects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CombatEffectDef"
      }
    }
  },
  "definitions": {
    "CombatEffectDef": {
      "type": "object",
      "properties": {
        "AuraCurse": {
          "type": "string"
        },
        "Charges": {
          "type": "integer"
        },
        "Target": {
          "type": "string",
          "enum": [
            "All",
            "Heroes",
            "Monsters",
            "Hero0",
            "Hero1",
            "Hero2",
            "Hero3",
            "Monster0",
            "Monster1",
            "Monster2",
            "Monster3"
          ]
        }
      }
    }
  }
}

=== Corgan/UnknownMod/Data/my_cool_test_mod/_patches/combats/csen_1.json
{
  "CombatId": "csen_1",
  "Description": "3 cornies",
  "NpcIds": [
    "cornie",
    "cornie",
    "blazingcornie",
    "advisor"
  ],
  "CombatTier": "T0",
  "Background": "Senenthia_Dia",
  "CustomBackgroundId": "my_cool_test_mod_new_zone_bg_0",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/zones/mycelium_abyss/combats/cmyc_10.json
{
  "CombatId": "cmyc_10",
  "Description": "Two colossal root-golems lumber out of the darkness.",
  "NpcIds": [
    "myc_golem",
    "myc_golem"
  ],
  "CombatTier": "T4",
  "Background": "Spider_Lair",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/combats/cmyc_10.json
{
  "CombatId": "cmyc_10",
  "Description": "A horde of mindless warriors surges forward, sustained by dark magic.",
  "NpcIds": [
    "myc_thrall",
    "myc_lurker",
    "myc_lurker",
    "myc_blightcaller"
  ],
  "CombatTier": "T4",
  "Background": "Sewers",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": [
    {
      "AuraCurse": "myc_symbiosis",
      "Charges": 1,
      "Target": "Monsters"
    }
  ]
}

=== Corgan/UnknownMod/Data/mycelium_abyss/zones/mycelium_abyss/combats/cmyc_1.json
{
  "CombatId": "cmyc_1",
  "Description": "Fungal scouts emerge from the cavern walls.",
  "NpcIds": [
    "myc_shambler",
    "myc_shambler",
    "myc_spitter"
  ],
  "CombatTier": "T3",
  "Background": "Spider_Lair",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/combats/emyc_15a.json
{
  "CombatId": "emyc_15a",
  "Description": "A massive root-creature blocks the path, flanked by scuttling shadows.",
  "NpcIds": [
    "myc_blightcaller",
    "myc_lurker",
    "myc_lurker"
  ],
  "CombatTier": "T3",
  "Background": "Velkarath_Cave",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/zones/mycelium_abyss/combats/cmyc_7.json
{
  "CombatId": "cmyc_7",
  "Description": "Twin casters channel the hivemind's fury behind a living wall.",
  "NpcIds": [
    "myc_blightcaller",
    "myc_blightcaller",
    "myc_golem"
  ],
  "CombatTier": "T4",
  "Background": "Spider_Lair",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/zones/mycelium_abyss/combats/cmyc_14.json
{
  "CombatId": "cmyc_boss",
  "Description": "The Mycelarch - heart of the hivemind - awaits at the network's core.",
  "NpcIds": [
    "myc_mycelarch",
    "myc_shambler",
    "myc_shambler"
  ],
  "CombatTier": "T5",
  "Background": "Spider_Lair",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}

=== Corgan/UnknownMod/Data/mycelium_abyss/combats/cmyc_w3.json
{
  "CombatId": "cmyc_w3",
  "Description": "A chorus of tiny sprouts shields a lumbering shambler.",
  "NpcIds": [
    "myc_sproutling",
    "myc_sproutling",
    "myc_shambler",
    ""
  ],
  "CombatTier": "T3",
  "Background": "Senenthia_BosqueEntrada_Nightmare",
  "NpcRemoveInMadness0Index": -1,
  "HealHeroes": false,
  "IsRift": false,
  "NpcToSummonOnKilledId": "",
  "EventDataId": "",
  "CombatEffects": []
}
