=== Corgan/UnknownMod/Data/_schema/LootDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LootDef",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "NumItems": {
      "type": "integer"
    },
    "GoldQuantity": {
      "type": "integer"
    },
    "AllowDropOnlyItems": {
      "type": "boolean"
    },
    "PercentUncommon": {
      "type": "number"
    },
    "PercentRare": {
      "type": "number"
    },
    "PercentEpic": {
      "type": "number"
    },
    "PercentMythic": {
      "type": "number"
    },
    "ShadyScaleX": {
      "type": "number"
    },
    "ShadyScaleY": {
      "type": "number"
    },
    "ShadyOffsetX": {
      "type": "number"
    },
    "ShadyOffsetY": {
      "type": "number"
    },
    "ShadyModelSource": {
      "type": "string"
    },
    "Items": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/LootItemDef"
      }
    }
  },
  "definitions": {
    "LootItemDef": {
      "type": "object",
      "properties": {
        "CardId": {
          "type": "string"
        },
        "Percent": {
          "type": "number"
        },
        "LootType": {
          "type": "string",
          "enum": [
            "None",
            "Melee_Attack",
            "Ranged_Attack",
            "Magic_Attack",
            "Defense",
            "Fire_Spell",
            "Cold_Spell",
            "Lightning_Spell",
            "Mind_Spell",
            "Shadow_Spell",
            "Holy_Spell",
            "Curse_Spell",
            "Healing_Spell",
            "Book",
            "Small_Weapon",
            "Song",
            "Skill",
            "Power",
            "Injury",
            "Attack",
            "Spell",
            "Boon",
            "Weapon",
            "Armor",
            "Jewelry",
            "Accesory",
            "Pet",
            "Corruption",
            "Enchantment",
            "Food",
            "Flask",
            "Petrare",
            "EchoEconomy",
            "EchoOverpowered",
            "Echo_Spell"
          ]
        },
        "LootRarity": {
          "type": "string",
          "enum": [
            "Common",
            "Uncommon",
            "Rare",
            "Epic",
            "Mythic"
          ]
        },
        "LootMisc": {
          "type": "string"
        }
      }
    }
  }
}

=== Corgan/UnknownMod/Data/mycelium_abyss/loot/myc_bossloot.json
{
  "Id": "myc_bossloot",
  "NumItems": 3,
  "GoldQuantity": 150,
  "PercentUncommon": 0,
  "PercentRare": 0,
  "PercentEpic": 60,
  "PercentMythic": 40,
  "Items": [
    {
      "CardId": "mycheartstaff",
      "Percent": 60,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycthronecarapace",
      "Percent": 60,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mychivesignet",
      "Percent": 60,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycheartsporereliquary",
      "Percent": 60,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    }
  ]
}

=== Corgan/UnknownMod/Data/mycelium_abyss/loot/myc_relicvault.json
{
  "Id": "myc_relicvault",
  "NumItems": 2,
  "GoldQuantity": 60,
  "Items": [
    {
      "CardId": "mycsporecapmantle",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycmycelialblade",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycsymbioticidol",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycfruitingcrown",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycrotstaff",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycthornbloomring",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycsporepouch",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    }
  ]
}

=== Corgan/UnknownMod/Data/mycelium_abyss/loot/myc_merchant.json
{
  "Id": "myc_merchant",
  "NumItems": 7,
  "PercentUncommon": 30,
  "PercentRare": 10,
  "Items": [
    {
      "CardId": "mycsporecapmantle",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycmycelialblade",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycsymbioticidol",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycfruitingcrown",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycrotstaff",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycthornbloomring",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "mycsporepouch",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "greaterhealthpotion",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "greatermanapotion",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "rejuvenationpotion",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    },
    {
      "CardId": "berserkpotion",
      "Percent": 100,
      "LootType": "None",
      "LootRarity": "Common",
      "LootMisc": ""
    }
  ]
}
