=== Corgan/UnknownMod/Data/_schema/NpcDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "NpcDef",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "SpriteSource": {
      "type": "string"
    },
    "HitSound": {
      "type": "string"
    },
    "HitSounds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "AnimTriggers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "AnimNoFallback": {
      "type": "boolean"
    },
    "VisualGraphId": {
      "type": "string"
    },
    "Portrait": {
      "type": "string"
    },
    "FlipPortrait": {
      "type": "boolean"
    },
    "PortraitScale": {
      "type": "number"
    },
    "PortraitOffsetX": {
      "type": "number"
    },
    "PortraitOffsetY": {
      "type": "number"
    },
    "Hp": {
      "type": "integer"
    },
    "Speed": {
      "type": "integer"
    },
    "Energy": {
      "type": "integer"
    },
    "EnergyTurn": {
      "type": "integer"
    },
    "CardsInHand": {
      "type": "integer"
    },
    "ResSlash": {
      "type": "integer"
    },
    "ResBlunt": {
      "type": "integer"
    },
    "ResPierce": {
      "type": "integer"
    },
    "ResFire": {
      "type": "integer"
    },
    "ResCold": {
      "type": "integer"
    },
    "ResLight": {
      "type": "integer"
    },
    "ResMind": {
      "type": "integer"
    },
    "ResHoly": {
      "type": "integer"
    },
    "ResShadow": {
      "type": "integer"
    },
    "AiCards": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/AiCardDef"
      }
    },
    "XpReward": {
      "type": "integer"
    },
    "GoldReward": {
      "type": "integer"
    },
    "TierReward": {
      "type": "integer"
    },
    "IsBoss": {
      "type": "boolean"
    },
    "IsNamed": {
      "type": "boolean"
    },
    "FinishCombatOnDead": {
      "type": "boolean"
    },
    "BigModel": {
      "type": "boolean"
    },
    "Female": {
      "type": "boolean"
    },
    "OnlyKillBossWhenHpZero": {
      "type": "boolean"
    },
    "Difficulty": {
      "type": "integer"
    },
    "PreferredPos": {
      "type": "string",
      "enum": [
        "Anywhere",
        "Front",
        "Random",
        "Back",
        "Middle",
        "Slowest",
        "Fastest",
        "LeastHP",
        "MostHP"
      ]
    },
    "FluffOffsetX": {
      "type": "number"
    },
    "FluffOffsetY": {
      "type": "number"
    },
    "PosBottom": {
      "type": "number"
    },
    "Immunities": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "UpgradedMobId": {
      "type": "string"
    },
    "NgPlusMobId": {
      "type": "string"
    },
    "HellModeMobId": {
      "type": "string"
    },
    "BaseNpcId": {
      "type": "string"
    },
    "HpMult": {
      "type": "number"
    },
    "SpeedBonus": {
      "type": "integer"
    },
    "ResistBonus": {
      "type": "integer"
    },
    "TierMob": {
      "type": "string",
      "enum": [
        "T0",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "T6",
        "T7",
        "T8",
        "T9",
        "T10",
        "T11",
        "T12",
        "T13"
      ]
    }
  },
  "definitions": {
    "AiCardDef": {
      "type": "object",
      "properties": {
        "CardId": {
          "type": "string"
        },
        "Priority": {
          "type": "integer"
        },
        "AddCardRound": {
          "type": "integer"
        },
        "OnlyCastIf": {
          "type": "string",
          "enum": [
            "Always",
            "TargetLifeLessThanPercent",
            "TargetHasNotAuraCurse",
            "TargetLifeHigherThanPercent",
            "TargetHasAuraCurse",
            "TargetHasAnyAura",
            "TargetHasAnyCurse",
            "TeamNpcAllAlive",
            "LifeInMainTargetHigherThanInSpecialTarget",
            "LifeInMainTargetLessThanInSpecialTarget",
            "TargetNotIllusion",
            "CasterHasMoreAuras",
            "AllCasterTeamNoSleepsOrParalyzed"
          ]
        },
        "ValueCastIf": {
          "type": "number"
        },
        "TargetCast": {
          "type": "string",
          "enum": [
            "Random",
            "Front",
            "Middle",
            "Back",
            "AnyButFront",
            "AnyButBack",
            "LessHealthPercent",
            "LessHealthFlat",
            "MoreHealthPercent",
            "MoreHealthFlat",
            "LessHealthAbsolute",
            "MoreHealthAbsolute",
            "LessInitiative",
            "MoreInitiative",
            "MoreAuraStacks"
          ]
        },
        "UnitsInDeck": {
          "type": "integer"
        },
        "PercentToCast": {
          "type": "number"
        },
        "StartsAtObeliskMadnessLevel": {
          "type": "integer"
        },
        "StartsAtSingularityMadnessLevel": {
          "type": "integer"
        },
        "AuracurseCastIf": {
          "type": "string"
        },
        "SecondOnlyCastIf": {
          "type": "string",
          "enum": [
            "Always",
            "TargetLifeLessThanPercent",
            "TargetHasNotAuraCurse",
            "TargetLifeHigherThanPercent",
            "TargetHasAuraCurse",
            "TargetHasAnyAura",
            "TargetHasAnyCurse",
            "TeamNpcAllAlive",
            "LifeInMainTargetHigherThanInSpecialTarget",
            "LifeInMainTargetLessThanInSpecialTarget",
            "TargetNotIllusion",
            "CasterHasMoreAuras",
            "AllCasterTeamNoSleepsOrParalyzed"
          ]
        },
        "SecondValueCastIf": {
          "type": "number"
        },
        "SpecialSecondTargetId": {
          "type": "string"
        }
      }
    }
  }
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_blightcaller_b.json
{
  "Id": "myc_blightcaller_b",
  "Name": "Blightcaller",
  "Description": "",
  "SpriteSource": "druid",
  "Hp": 274,
  "Speed": 15,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 9,
  "ResBlunt": 9,
  "ResPierce": 9,
  "ResFire": -6,
  "ResCold": 19,
  "ResLight": 14,
  "ResMind": 34,
  "ResHoly": -1,
  "ResShadow": 39,
  "AiCards": [
    {
      "CardId": "mycmiasma",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycfungalregen",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.6,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 48,
  "GoldReward": 46,
  "TierReward": 5,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Female": false,
  "OnlyKillBossWhenHpZero": false,
  "Difficulty": -1,
  "PreferredPos": "Back",
  "FluffOffsetX": 0.0,
  "FluffOffsetY": 0.0,
  "PosBottom": 0.0,
  "Immunities": [],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_devourer_plus_b.json
{
  "Id": "myc_devourer_plus_b",
  "Name": "Rotmaw Devourer",
  "Description": "",
  "SpriteSource": "swamphorror",
  "Hp": 344,
  "Speed": 16,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 28,
  "ResBlunt": 28,
  "ResPierce": 23,
  "ResFire": 3,
  "ResCold": 18,
  "ResLight": 8,
  "ResMind": 18,
  "ResHoly": 8,
  "ResShadow": 38,
  "AiCards": [
    {
      "CardId": "mycrotmawbitea",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycgorgea",
      "Priority": 3,
      "AddCardRound": 2,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 41,
  "GoldReward": 37,
  "TierReward": 4,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "Immunities": [],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_lurker_b.json
{
  "Id": "myc_lurker_b",
  "Name": "Mycelium Lurker",
  "Description": "",
  "SpriteSource": "spider",
  "Hp": 156,
  "Speed": 19,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 9,
  "ResBlunt": 4,
  "ResPierce": 19,
  "ResFire": -6,
  "ResCold": 29,
  "ResLight": -1,
  "ResMind": 29,
  "ResHoly": 9,
  "ResShadow": 24,
  "AiCards": [
    {
      "CardId": "mycrootsnare",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsymbioticdrain",
      "Priority": 4,
      "AddCardRound": 0,
      "OnlyCastIf": "TargetLifeLessThanPercent",
      "ValueCastIf": 0.7,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycrotbite",
      "Priority": 5,
      "AddCardRound": 1,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 28,
  "GoldReward": 26,
  "TierReward": 4,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Back",
  "Immunities": [],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_golem_b.json
{
  "Id": "myc_golem_b",
  "Name": "Mycelium Golem",
  "Description": "",
  "SpriteSource": "trunky",
  "Hp": 313,
  "Speed": 9,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 34,
  "ResBlunt": 39,
  "ResPierce": 24,
  "ResFire": -6,
  "ResCold": 19,
  "ResLight": -1,
  "ResMind": 14,
  "ResHoly": 9,
  "ResShadow": 29,
  "AiCards": [
    {
      "CardId": "myccrushingroot",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycbarkshield",
      "Priority": 7,
      "AddCardRound": 0,
      "OnlyCastIf": "TargetHasNotAuraCurse",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "thorns",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsymbioticbloom",
      "Priority": 4,
      "AddCardRound": 2,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 55,
  "GoldReward": 52,
  "TierReward": 5,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": true,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "Immunities": [],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_spitter_plus_b.json
{
  "Id": "myc_spitter_plus_b",
  "Name": "Gloom Spitter",
  "Description": "",
  "SpriteSource": "slime",
  "Hp": 184,
  "Speed": 18,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 13,
  "ResBlunt": 18,
  "ResPierce": 8,
  "ResFire": -2,
  "ResCold": 33,
  "ResLight": 18,
  "ResMind": 28,
  "ResHoly": 18,
  "ResShadow": 43,
  "AiCards": [
    {
      "CardId": "mycacidgloba",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "myctoxicpuddlea",
      "Priority": 4,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 24,
  "GoldReward": 22,
  "TierReward": 4,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Back",
  "Immunities": [],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_sproutling.json
{
  "Id": "myc_sproutling",
  "Name": "Sporebloom Sprout",
  "Description": "",
  "SpriteSource": "sapling",
  "Hp": 70,
  "Speed": 17,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 0,
  "ResBlunt": 0,
  "ResPierce": 0,
  "ResFire": -20,
  "ResCold": 0,
  "ResLight": 0,
  "ResMind": 5,
  "ResHoly": -10,
  "ResShadow": 15,
  "AiCards": [
    {
      "CardId": "mycsproutgift",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "TargetHasNotAuraCurse",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "myc_symbiosis",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsproutlash",
      "Priority": 3,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 28,
  "GoldReward": 26,
  "TierReward": 3,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Back",
  "Immunities": [],
  "UpgradedMobId": "myc_sproutling_b",
  "NgPlusMobId": "myc_sproutling_plus",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T1"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_mycelarch_plus_b.json
{
  "Id": "myc_mycelarch_plus_b",
  "Name": "The Mycelarch",
  "Description": "",
  "SpriteSource": "elderdryad",
  "Hp": 672,
  "Speed": 16,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 4,
  "ResSlash": 34,
  "ResBlunt": 29,
  "ResPierce": 29,
  "ResFire": -1,
  "ResCold": 34,
  "ResLight": 9,
  "ResMind": 44,
  "ResHoly": 4,
  "ResShadow": 54,
  "AiCards": [
    {
      "CardId": "myctoxicraina",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycfungalbarriera",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsporevolleya",
      "Priority": 4,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsporespawna",
      "Priority": 3,
      "AddCardRound": 1,
      "OnlyCastIf": "Always",
      "ValueCastIf": 3.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mychallucinobursta",
      "Priority": 7,
      "AddCardRound": 3,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycpandemica",
      "Priority": 6,
      "AddCardRound": 3,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "MoreHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycneurallinka",
      "Priority": 8,
      "AddCardRound": 3,
      "OnlyCastIf": "TargetHasNotAuraCurse",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "powerful",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycmyceliumapoca",
      "Priority": 9,
      "AddCardRound": 6,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 170,
  "GoldReward": 140,
  "TierReward": 9,
  "IsBoss": true,
  "IsNamed": false,
  "FinishCombatOnDead": true,
  "BigModel": true,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "Immunities": [
    "paralyze",
    "sleep",
    "doom"
  ],
  "UpgradedMobId": "",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T2"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_shambler_plus.json
{
  "Id": "myc_shambler_plus",
  "Name": "Sporecap Shambler",
  "Description": "",
  "SpriteSource": "treant",
  "Hp": 147,
  "Speed": 11,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 19,
  "ResBlunt": 24,
  "ResPierce": 14,
  "ResFire": -11,
  "ResCold": 19,
  "ResLight": 9,
  "ResMind": 24,
  "ResHoly": -6,
  "ResShadow": 34,
  "AiCards": [
    {
      "CardId": "myctoxicslama",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsporemista",
      "Priority": 3,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 28,
  "GoldReward": 26,
  "TierReward": 4,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "Immunities": [],
  "UpgradedMobId": "myc_shambler_plus_b",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T1"
}
