=== Corgan/UnknownMod/Data/_schema/NpcDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "NpcDef",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "SpriteSource": {
      "type": "string"
    },
    "HitSound": {
      "type": "string"
    },
    "HitSounds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "AnimTriggers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "AnimNoFallback": {
      "type": "boolean"
    },
    "VisualGraphId": {
      "type": "string"
    },
    "Portrait": {
      "type": "string"
    },
    "FlipPortrait": {
      "type": "boolean"
    },
    "PortraitScale": {
      "type": "number"
    },
    "PortraitOffsetX": {
      "type": "number"
    },
    "PortraitOffsetY": {
      "type": "number"
    },
    "Hp": {
      "type": "integer"
    },
    "Speed": {
      "type": "integer"
    },
    "Energy": {
      "type": "integer"
    },
    "EnergyTurn": {
      "type": "integer"
    },
    "CardsInHand": {
      "type": "integer"
    },
    "ResSlash": {
      "type": "integer"
    },
    "ResBlunt": {
      "type": "integer"
    },
    "ResPierce": {
      "type": "integer"
    },
    "ResFire": {
      "type": "integer"
    },
    "ResCold": {
      "type": "integer"
    },
    "ResLight": {
      "type": "integer"
    },
    "ResMind": {
      "type": "integer"
    },
    "ResHoly": {
      "type": "integer"
    },
    "ResShadow": {
      "type": "integer"
    },
    "AiCards": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/AiCardDef"
      }
    },
    "XpReward": {
      "type": "integer"
    },
    "GoldReward": {
      "type": "integer"
    },
    "TierReward": {
      "type": "integer"
    },
    "IsBoss": {
      "type": "boolean"
    },
    "IsNamed": {
      "type": "boolean"
    },
    "FinishCombatOnDead": {
      "type": "boolean"
    },
    "BigModel": {
      "type": "boolean"
    },
    "Female": {
      "type": "boolean"
    },
    "OnlyKillBossWhenHpZero": {
      "type": "boolean"
    },
    "Difficulty": {
      "type": "integer"
    },
    "PreferredPos": {
      "type": "string",
      "enum": [
        "Anywhere",
        "Front",
        "Random",
        "Back",
        "Middle",
        "Slowest",
        "Fastest",
        "LeastHP",
        "MostHP"
      ]
    },
    "FluffOffsetX": {
      "type": "number"
    },
    "FluffOffsetY": {
      "type": "number"
    },
    "PosBottom": {
      "type": "number"
    },
    "Immunities": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "UpgradedMobId": {
      "type": "string"
    },
    "NgPlusMobId": {
      "type": "string"
    },
    "HellModeMobId": {
      "type": "string"
    },
    "BaseNpcId": {
      "type": "string"
    },
    "HpMult": {
      "type": "number"
    },
    "SpeedBonus": {
      "type": "integer"
    },
    "ResistBonus": {
      "type": "integer"
    },
    "TierMob": {
      "type": "string",
      "enum": [
        "T0",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "T6",
        "T7",
        "T8",
        "T9",
        "T10",
        "T11",
        "T12",
        "T13"
      ]
    }
  },
  "definitions": {
    "AiCardDef": {
      "type": "object",
      "properties": {
        "CardId": {
          "type": "string"
        },
        "Priority": {
          "type": "integer"
        },
        "AddCardRound": {
          "type": "integer"
        },
        "OnlyCastIf": {
          "type": "string",
          "enum": [
            "Always",
            "TargetLifeLessThanPercent",
            "TargetHasNotAuraCurse",
            "TargetLifeHigherThanPercent",
            "TargetHasAuraCurse",
            "TargetHasAnyAura",
            "TargetHasAnyCurse",
            "TeamNpcAllAlive",
            "LifeInMainTargetHigherThanInSpecialTarget",
            "LifeInMainTargetLessThanInSpecialTarget",
            "TargetNotIllusion",
            "CasterHasMoreAuras",
            "AllCasterTeamNoSleepsOrParalyzed"
          ]
        },
        "ValueCastIf": {
          "type": "number"
        },
        "TargetCast": {
          "type": "string",
          "enum": [
            "Random",
            "Front",
            "Middle",
            "Back",
            "AnyButFront",
            "AnyButBack",
            "LessHealthPercent",
            "LessHealthFlat",
            "MoreHealthPercent",
            "MoreHealthFlat",
            "LessHealthAbsolute",
            "MoreHealthAbsolute",
            "LessInitiative",
            "MoreInitiative",
            "MoreAuraStacks"
          ]
        },
        "UnitsInDeck": {
          "type": "integer"
        },
        "PercentToCast": {
          "type": "number"
        },
        "StartsAtObeliskMadnessLevel": {
          "type": "integer"
        },
        "StartsAtSingularityMadnessLevel": {
          "type": "integer"
        },
        "AuracurseCastIf": {
          "type": "string"
        },
        "SecondOnlyCastIf": {
          "type": "string",
          "enum": [
            "Always",
            "TargetLifeLessThanPercent",
            "TargetHasNotAuraCurse",
            "TargetLifeHigherThanPercent",
            "TargetHasAuraCurse",
            "TargetHasAnyAura",
            "TargetHasAnyCurse",
            "TeamNpcAllAlive",
            "LifeInMainTargetHigherThanInSpecialTarget",
            "LifeInMainTargetLessThanInSpecialTarget",
            "TargetNotIllusion",
            "CasterHasMoreAuras",
            "AllCasterTeamNoSleepsOrParalyzed"
          ]
        },
        "SecondValueCastIf": {
          "type": "number"
        },
        "SpecialSecondTargetId": {
          "type": "string"
        }
      }
    }
  }
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_lurker_plus.json
{
  "Id": "myc_lurker_plus",
  "Name": "Mycelium Lurker",
  "Description": "",
  "SpriteSource": "spider",
  "Hp": 124,
  "Speed": 19,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 9,
  "ResBlunt": 4,
  "ResPierce": 19,
  "ResFire": -6,
  "ResCold": 29,
  "ResLight": -1,
  "ResMind": 29,
  "ResHoly": 9,
  "ResShadow": 24,
  "AiCards": [
    {
      "CardId": "mycrootsnarea",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsymbioticdraina",
      "Priority": 4,
      "AddCardRound": 0,
      "OnlyCastIf": "TargetLifeLessThanPercent",
      "ValueCastIf": 0.7,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycrotbitea",
      "Priority": 5,
      "AddCardRound": 1,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 24,
  "GoldReward": 22,
  "TierReward": 4,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Back",
  "Immunities": [],
  "UpgradedMobId": "myc_lurker_plus_b",
  "NgPlusMobId": "",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T1"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_thrall.json
{
  "Id": "myc_thrall",
  "Name": "Cordyceps Thrall",
  "Description": "",
  "SpriteSource": "bonefighter",
  "Hp": 126,
  "Speed": 12,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 2,
  "ResSlash": 15,
  "ResBlunt": 20,
  "ResPierce": 5,
  "ResFire": 5,
  "ResCold": 0,
  "ResLight": -15,
  "ResMind": -10,
  "ResHoly": -20,
  "ResShadow": 15,
  "AiCards": [
    {
      "CardId": "mycmindlesscharge",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "LessHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycfungalburst",
      "Priority": 3,
      "AddCardRound": 2,
      "OnlyCastIf": "Always",
      "ValueCastIf": 3.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 33,
  "GoldReward": 30,
  "TierReward": 3,
  "IsBoss": false,
  "IsNamed": false,
  "FinishCombatOnDead": false,
  "BigModel": false,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "Immunities": [],
  "UpgradedMobId": "myc_thrall_b",
  "NgPlusMobId": "myc_thrall_plus",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T1"
}

=== Corgan/UnknownMod/Data/mycelium_abyss/npcs/myc_mycelarch.json
{
  "Id": "myc_mycelarch",
  "Name": "The Mycelarch",
  "Description": "",
  "SpriteSource": "elderdryad",
  "Hp": 420,
  "Speed": 14,
  "Energy": 10,
  "EnergyTurn": 0,
  "CardsInHand": 4,
  "ResSlash": 15,
  "ResBlunt": 10,
  "ResPierce": 10,
  "ResFire": -20,
  "ResCold": 15,
  "ResLight": -10,
  "ResMind": 25,
  "ResHoly": -15,
  "ResShadow": 35,
  "AiCards": [
    {
      "CardId": "myctoxicrain",
      "Priority": 5,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycfungalbarrier",
      "Priority": 6,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsporevolley",
      "Priority": 4,
      "AddCardRound": 0,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycsporespawn",
      "Priority": 3,
      "AddCardRound": 1,
      "OnlyCastIf": "Always",
      "ValueCastIf": 3.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mychallucinoburst",
      "Priority": 7,
      "AddCardRound": 3,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycpandemic",
      "Priority": 6,
      "AddCardRound": 3,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "MoreHealthPercent",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycneurallink",
      "Priority": 8,
      "AddCardRound": 3,
      "OnlyCastIf": "TargetHasNotAuraCurse",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "powerful",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    },
    {
      "CardId": "mycmyceliumapoc",
      "Priority": 9,
      "AddCardRound": 6,
      "OnlyCastIf": "Always",
      "ValueCastIf": 0.0,
      "TargetCast": "Random",
      "UnitsInDeck": 1,
      "PercentToCast": 0.0,
      "StartsAtObeliskMadnessLevel": 0,
      "StartsAtSingularityMadnessLevel": 0,
      "AuracurseCastIf": "",
      "SecondOnlyCastIf": "Always",
      "SecondValueCastIf": 0.0
    }
  ],
  "XpReward": 120,
  "GoldReward": 120,
  "TierReward": 7,
  "IsBoss": true,
  "IsNamed": false,
  "FinishCombatOnDead": true,
  "BigModel": true,
  "Female": false,
  "OnlyKillBossWhenHpZero": false,
  "Difficulty": -1,
  "PreferredPos": "Front",
  "FluffOffsetX": 0.0,
  "FluffOffsetY": 0.0,
  "PosBottom": 0.0,
  "Immunities": [
    "paralyze",
    "sleep",
    "doom"
  ],
  "UpgradedMobId": "myc_mycelarch_b",
  "NgPlusMobId": "myc_mycelarch_plus",
  "HellModeMobId": "",
  "BaseNpcId": "",
  "HpMult": 1.0,
  "SpeedBonus": 0,
  "ResistBonus": 0,
  "TierMob": "T1"
}
