=== Corgan/UnknownMod/Data/_schema/PerkNodeDef.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PerkNodeDef",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Type": {
      "type": "integer"
    },
    "Column": {
      "type": "integer"
    },
    "Row": {
      "type": "integer"
    },
    "LockedInTown": {
      "type": "boolean"
    },
    "NotStack": {
      "type": "boolean"
    },
    "Cost": {
      "type": "string",
      "enum": [
        "PerkCostBase",
        "PerkCostAdvanced"
      ]
    },
    "Perk": {
      "type": "string"
    },
    "PerkRequired": {
      "type": "string"
    },
    "PerksConnected": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "SpriteSource": {
      "type": "string"
    }
  }
}

=== Corgan/UnknownMod/Data/mycelium_abyss/perknodes/nodeperkmycsym2.json
{
  "Id": "nodeperkmycsym2",
  "Type": 3,
  "Column": -2,
  "Row": 3,
  "NotStack": false,
  "Cost": "PerkCostAdvanced",
  "Perk": "",
  "PerkRequired": "nodeperkmycsym0",
  "PerksConnected": [
    "nodeperkmycsym2a",
    "nodeperkmycsym2b",
    "nodeperkmycsym2c",
    "nodeperkmycsym2d"
  ],
  "SpriteSource": "aura:myc_symbiosis"
}
